packaging_format = 2

id = "uptime-kuma"
name = "Uptime Kuma"
description.en = "Monitoring tool like Uptime-Robot"
description.fr = "Outil de surveillance similaire à Uptime-Robot"

version = "1.20.2~ynh1"

maintainers = ["Hadrien"]

[upstream]
license = "MIT"
website = "https://uptime.kuma.pet/"
demo = "https://demo.uptime.kuma.pet"
userdoc = "https://github.com/louislam/uptime-kuma/wiki"
code = "https://github.com/louislam/uptime-kuma"

[integration]
yunohost = ">= 11.1.15"
architectures = [ "amd64" ]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "This app has a status page meant to be public and a login-protected admin interface. It should be safe to expose publicly."
    help.fr = "Cette app a une page destinée à être publique et une interface d'admin protégée par mot de passe. Elle peut être exposée publiquement sans problème."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.dist]
        url = "https://github.com/louislam/uptime-kuma/releases/download/1.20.2/dist.tar.gz"
        sha256 = "41f0fe9f1d9ec432c98e8bce2f25b59dd61c11f774bd2ad53d5cec1d795fd782"

        [resources.sources.main]
        url = "https://github.com/louislam/uptime-kuma/archive/refs/tags/1.20.2.tar.gz"
        sha256 = "9febdad8bb24caee012a0c79cada6aace88ad3859cf94218512df987ecda009f"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true
