packaging_format = 2

id = "uptime-kuma"
name = "Uptime Kuma"
description.en = "Monitoring tool like Uptime-Robot"
description.fr = "Outil de surveillance similaire à Uptime-Robot"

version = "1.22.1~ynh1"

maintainers = ["ketsapiwiq", "eric_G"]

[upstream]
license = "MIT"
website = "https://uptime.kuma.pet/"
demo = "https://demo.uptime.kuma.pet"
userdoc = "https://github.com/louislam/uptime-kuma/wiki"
code = "https://github.com/louislam/uptime-kuma"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "This app has a status page meant to be public and a login-protected admin interface. It should be safe to expose publicly."
    help.fr = "Cette app a une page destinée à être publique et une interface d'admin protégée par mot de passe. Elle peut être exposée publiquement sans problème."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.dist]
        url = "https://github.com/louislam/uptime-kuma/releases/download/1.22.1/dist.tar.gz"
        sha256 = "212ec06db9a29c668ee3b4814dd9c7c167be9baf627eed160aee18399c3064e4"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "dist.tar.gz"

        [resources.sources.main]
        url = "https://github.com/louislam/uptime-kuma/archive/refs/tags/1.22.1.tar.gz"
        sha256 = "1b72331853178b82bc18673a207680d9a999c5a84e296418278084f5206fb91b"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "tarball"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true
