packaging_format = 2

id = "uptime-kuma"
name = "Uptime Kuma"
description.en = "Self-hosted monitoring tool like Uptime-Robot"
description.fr = "Outil de surveillance auto-hébergé similaire à Uptime-Robot"

version = "1.20.2~ynh1"

maintainers = ["Hadrien"]

[upstream]
license = "MIT"
website = "https://uptime.kuma.pet/"
demo = "https://demo.uptime.kuma.pet"
admindoc = "https://github.com/louislam/uptime-kuma/wiki"
userdoc = "https://github.com/louislam/uptime-kuma/wiki"
code = "https://github.com/louislam/uptime-kuma"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.2.3"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    help.en = "This app requires a whole subdomain"
    help.fr = "Cette app a besoin de tout un sous-domaine à elle toute seule."
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "This app has a status page meant to be public and a login-protected admin interface. It should be safe to expose publicly."
    help.fr = "Cette app a une page destinée à être publique et une interface d'admin protégée par mot de passe. Elle peut être exposée publiquement sans problème."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.dist]
        url = "https://github.com/louislam/uptime-kuma/releases/download/1.20.2/dist.tar.gz"
        sha256 = "41f0fe9f1d9ec432c98e8bce2f25b59dd61c11f774bd2ad53d5cec1d795fd782"

        [resources.sources.main]
        url = "https://github.com/louislam/uptime-kuma/archive/refs/tags/1.20.2.tar.gz"
        sha256 = "9febdad8bb24caee012a0c79cada6aace88ad3859cf94218512df987ecda009f"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
