packaging_format = 2

id = "uptime-kuma"
name = "Uptime Kuma"
description.en = "Monitoring tool like Uptime-Robot"
description.fr = "Outil de surveillance similaire à Uptime-Robot"

version = "1.23.3~ynh1"

maintainers = ["ketsapiwiq", "eric_G"]

[upstream]
license = "MIT"
website = "https://uptime.kuma.pet/"
demo = "https://demo.uptime.kuma.pet"
userdoc = "https://github.com/louislam/uptime-kuma/wiki"
code = "https://github.com/louislam/uptime-kuma"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "700M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "This app has a status page meant to be public and a login-protected admin interface. It should be safe to expose publicly."
    help.fr = "Cette app a une page destinée à être publique et une interface d'admin protégée par mot de passe. Elle peut être exposée publiquement sans problème."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.dist]
        url = "https://github.com/louislam/uptime-kuma/releases/download/1.23.3/dist.tar.gz"
        sha256 = "33db6e2061f1df75ad7e138d81edb1050b1814c0d94ada8e50e5da76e86edb90"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "dist.tar.gz"

        [resources.sources.main]
        url = "https://github.com/louislam/uptime-kuma/archive/refs/tags/1.23.3.tar.gz"
        sha256 = "5678c7f801fd08b8cffe88e22002e3411608542314b63c68aa028cf53b31ff26"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "tarball"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true
