test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.484a6b12681415f6cc031ed3279795ce1a8b29cc.name = "Upgrade from 1.20.2"